server:
  port: 8081

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: admin
      port: 27017
      host: localhost
      uri: mongodb://root:root@localhost:27017/admin

      
      